spring:
  datasource:
    url: jdbc:mysql://mysql_core_db:3306/banking_core_service
    username: javatodev_development
    password: oPItyPticIAt
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://internet-banking-service-registry:8081/eureka

info:
  app:
    name: ${spring.application.name}
