spring:
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/banking_core_service
    username: javatodev_development
    password: oPItyPticIAt
  jpa:
    hibernate:
      ddl-auto: none
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    base-url: http://192.168.1.5:9411
    enabled: true
    service:
      name: ${spring.application.name}


server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.5:8081/eureka

info:
  app:
    name: ${spring.application.name}
