server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://mysql_core_db:3306/banking_core_utility_payment_service
    username: javatodev_development
    password: oPItyPticIAt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://internet-banking-service-registry:8081/eureka

info:
  app:
    name: ${spring.application.name}
