server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/banking_core_utility_payment_service
    username: javatodev_development
    password: oPItyPticIAt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    base-url: http://192.168.1.5:9411
    enabled: true
    service:
      name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.5:8081/eureka

info:
  app:
    name: ${spring.application.name}
